services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache_solmeil
    ports:
      - "8083:80"
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    mem_limit: 512m
    cpus: 0.5

  mysql:
    image: mysql:8.0
    container_name: mysql_solmeil
    restart: unless-stopped
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rubitdb
      MYSQL_USER: rubituser
      MYSQL_PASSWORD: 
    volumes:
      - db_data:/var/lib/mysql
    mem_limit: 512m
    cpus: 0.5

volumes:
  db_data:
